/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: set.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "set.pb-c.h"
void   proto_tf64__weights__init
                     (ProtoTf64__Weights         *message)
{
  static const ProtoTf64__Weights init_value = PROTO_TF64__WEIGHTS__INIT;
  *message = init_value;
}
size_t proto_tf64__weights__get_packed_size
                     (const ProtoTf64__Weights *message)
{
  assert(message->base.descriptor == &proto_tf64__weights__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_tf64__weights__pack
                     (const ProtoTf64__Weights *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_tf64__weights__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_tf64__weights__pack_to_buffer
                     (const ProtoTf64__Weights *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_tf64__weights__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoTf64__Weights *
       proto_tf64__weights__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoTf64__Weights *)
     protobuf_c_message_unpack (&proto_tf64__weights__descriptor,
                                allocator, len, data);
}
void   proto_tf64__weights__free_unpacked
                     (ProtoTf64__Weights *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_tf64__weights__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_tf64__set__init
                     (ProtoTf64__Set         *message)
{
  static const ProtoTf64__Set init_value = PROTO_TF64__SET__INIT;
  *message = init_value;
}
size_t proto_tf64__set__get_packed_size
                     (const ProtoTf64__Set *message)
{
  assert(message->base.descriptor == &proto_tf64__set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_tf64__set__pack
                     (const ProtoTf64__Set *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_tf64__set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_tf64__set__pack_to_buffer
                     (const ProtoTf64__Set *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_tf64__set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoTf64__Set *
       proto_tf64__set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoTf64__Set *)
     protobuf_c_message_unpack (&proto_tf64__set__descriptor,
                                allocator, len, data);
}
void   proto_tf64__set__free_unpacked
                     (ProtoTf64__Set *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_tf64__set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto_tf64__weights__field_descriptors[4] =
{
  {
    "Name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoTf64__Weights, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Shape",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ProtoTf64__Weights, n_shape),
    offsetof(ProtoTf64__Weights, shape),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Values",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(ProtoTf64__Weights, n_values),
    offsetof(ProtoTf64__Weights, values),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "States",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(ProtoTf64__Weights, n_states),
    offsetof(ProtoTf64__Weights, states),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_tf64__weights__field_indices_by_name[] = {
  0,   /* field[0] = Name */
  1,   /* field[1] = Shape */
  3,   /* field[3] = States */
  2,   /* field[2] = Values */
};
static const ProtobufCIntRange proto_tf64__weights__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto_tf64__weights__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto_tf64.Weights",
  "Weights",
  "ProtoTf64__Weights",
  "proto_tf64",
  sizeof(ProtoTf64__Weights),
  4,
  proto_tf64__weights__field_descriptors,
  proto_tf64__weights__field_indices_by_name,
  1,  proto_tf64__weights__number_ranges,
  (ProtobufCMessageInit) proto_tf64__weights__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_tf64__set__field_descriptors[3] =
{
  {
    "Cost",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ProtoTf64__Set, cost),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Epoch",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ProtoTf64__Set, epoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Weights",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtoTf64__Set, n_weights),
    offsetof(ProtoTf64__Set, weights),
    &proto_tf64__weights__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_tf64__set__field_indices_by_name[] = {
  0,   /* field[0] = Cost */
  1,   /* field[1] = Epoch */
  2,   /* field[2] = Weights */
};
static const ProtobufCIntRange proto_tf64__set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto_tf64__set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto_tf64.Set",
  "Set",
  "ProtoTf64__Set",
  "proto_tf64",
  sizeof(ProtoTf64__Set),
  3,
  proto_tf64__set__field_descriptors,
  proto_tf64__set__field_indices_by_name,
  1,  proto_tf64__set__number_ranges,
  (ProtobufCMessageInit) proto_tf64__set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
