/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: set.proto */

#ifndef PROTOBUF_C_set_2eproto__INCLUDED
#define PROTOBUF_C_set_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct ProtoTf64__Weights ProtoTf64__Weights;
typedef struct ProtoTf64__Set ProtoTf64__Set;


/* --- enums --- */


/* --- messages --- */

struct  ProtoTf64__Weights
{
  ProtobufCMessage base;
  char *name;
  size_t n_shape;
  int64_t *shape;
  size_t n_values;
  double *values;
  size_t n_states;
  double *states;
};
#define PROTO_TF64__WEIGHTS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto_tf64__weights__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, 0,NULL }


struct  ProtoTf64__Set
{
  ProtobufCMessage base;
  double cost;
  uint64_t epoch;
  size_t n_weights;
  ProtoTf64__Weights **weights;
};
#define PROTO_TF64__SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto_tf64__set__descriptor) \
    , 0, 0, 0,NULL }


/* ProtoTf64__Weights methods */
void   proto_tf64__weights__init
                     (ProtoTf64__Weights         *message);
size_t proto_tf64__weights__get_packed_size
                     (const ProtoTf64__Weights   *message);
size_t proto_tf64__weights__pack
                     (const ProtoTf64__Weights   *message,
                      uint8_t             *out);
size_t proto_tf64__weights__pack_to_buffer
                     (const ProtoTf64__Weights   *message,
                      ProtobufCBuffer     *buffer);
ProtoTf64__Weights *
       proto_tf64__weights__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto_tf64__weights__free_unpacked
                     (ProtoTf64__Weights *message,
                      ProtobufCAllocator *allocator);
/* ProtoTf64__Set methods */
void   proto_tf64__set__init
                     (ProtoTf64__Set         *message);
size_t proto_tf64__set__get_packed_size
                     (const ProtoTf64__Set   *message);
size_t proto_tf64__set__pack
                     (const ProtoTf64__Set   *message,
                      uint8_t             *out);
size_t proto_tf64__set__pack_to_buffer
                     (const ProtoTf64__Set   *message,
                      ProtobufCBuffer     *buffer);
ProtoTf64__Set *
       proto_tf64__set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto_tf64__set__free_unpacked
                     (ProtoTf64__Set *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ProtoTf64__Weights_Closure)
                 (const ProtoTf64__Weights *message,
                  void *closure_data);
typedef void (*ProtoTf64__Set_Closure)
                 (const ProtoTf64__Set *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto_tf64__weights__descriptor;
extern const ProtobufCMessageDescriptor proto_tf64__set__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_set_2eproto__INCLUDED */
